language: node_js

node_js:
  - node
  - 'lts/*'

cache: npm

jobs:
  include:
    - stage: Lint
      node_js: node
      script: npm run lint
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
