dist: xenial
language: node_js
env:
  global:
    - DISPLAY=:99.0

node_js:
  - node
  - 'lts/*'

addons:
  chrome: stable

services:
  - xvfb

cache: npm

before_script:
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.12/bin/
  - export CHROME_BIN=chromium-browser

jobs:
  include:
#    - stage: Lint
#      node_js: node
#      script: npm run lint
#    - stage: Test Unit
#      node_js: node
#      script: npm run test:unit
    - stage: Test e2e
      node_js: node
      script: chromium-browser --version && xvfb-run -a npm run test:e2e

